# Generated by Django 4.0.4 on 2022-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta de calorias'),
        ),
    ]
