# Generated by Django 4.0.4 on 2022-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Calorias atuais'),
        ),
    ]
