# Generated by Django 4.0.4 on 2022-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
