# Generated by Django 4.0.4 on 2022-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_alter_meal_name_alter_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='measure',
            field=models.CharField(choices=[('G', 'Gramas'), ('MG', 'Mili Gramas'), ('L', 'Litros'), ('ML', 'Mili Litros')], max_length=2, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
