# Generated by Django 4.0.4 on 2022-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_food_measure_alter_food_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='measure',
            field=models.CharField(choices=[('G', 'Gramas'), ('L', 'Litros'), ('ML', 'Mili Litros')], max_length=2, verbose_name='Medida'),
        ),
    ]
