# Generated by Django 4.0.4 on 2022-04-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_food_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Calorias'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates_total',
            field=models.DecimalField(decimal_places=1, max_digits=20, verbose_name='Carboidratos'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.PositiveIntegerField(verbose_name='Colesterol'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_saturated',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Gordura Saturada'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_total',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Gorduras Totais'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Fibra'),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.PositiveIntegerField(verbose_name='Potassio'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Proteínas'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.PositiveIntegerField(verbose_name='Sodio'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Açucar'),
        ),
    ]
